
###

# REGISTER

POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "email": "jackietest1@test.com",
  "username": "jackieTest",
  "password": "password"
}

### 

# LOGIN SUCCESS

POST http://localhost:3002/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "username": "yeyoteef",
  "password": "password"
}


### 

# SEARCH SUCCESS

GET http://localhost:3002/api/v1/search/espinalhe1 HTTP/1.1

###

# CREATE LOAN

POST http://localhost:3002/api/v1/loan HTTP/1.1
Content-Type: application/json

{
  "lender": "fromRefactorSrc1",
  "borrower": "yeyoteef",
  "status": "pending",
  "creation_date": "2022-11-18T04:00:00.000Z",
  "due_date": "2022-11-30T04:00:00.000Z",
  "amount": "10.00",
  "description": "jackie TEST CREATING NEW LOAN",
  "payment_date": "2022-11-30",
  "transaction_rating": 0
}

### 

# UPDATE LOAN

PUT http://localhost:3002/api/v1/loan HTTP/1.1
Content-Type: application/json

{
  "loan_id": 64,
  "lender": "fromRefactorSrc1",
  "borrower": "yeyoteef",
  "status": "paid",
  "creation_date": "2022-11-18T04:00:00.000Z",
  "due_date": "2022-11-30T04:00:00.000Z",
  "amount": "1000000.00",
  "description": "jackie UPDATING LOAN TEST-- status PAID",
  "payment_date": "2022-11-30T04:00:00.000Z",
  "transaction_rating": 1
}

### 

# VALIDATE TOKEN

GET http://localhost:3002/api/v1/validate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlleW90ZWVmIiwiaWF0IjoxNjY4ODI3NDk4LCJleHAiOjE2Njg4MjgwOTh9.QYM7uAXumKTjRTK8kowuOo4J7v4tWrqx36OuSaoQcLs

###


# REFETCH USER

GET http://localhost:3002/api/v1/yeyoteef/validate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlleW90ZWVmIiwiaWF0IjoxNjcwMDg5OTAwLCJleHAiOjE2NzAwOTM1MDB9.RHn031tVD51J7Zd52ZpYyoHt9sMi2tVjeOyJ_s44Aok

###

# UPDATE USER? INACTIVE ROUTE/DO NOT RUN

PUT http://localhost:3002/api/v1/yeyoteef/update HTTP/1.1
Content-Type: application/json

{ 
  "username": "yeyoteef",
  "reputation": 3, 
  "total_borrowing": 12, 
  "total_lending": 22, 
  "total_score": 200
}


# FETCH ADMIN DASHBOARD DATA
GET http://localhost:3002/api/v1/data/admin HTTP/1.1

###

